### ISSUE TITLE
Bad version declared #14 is still not fixed

### ISSUE THREAD

**Issue by JonAStorelv** [pulumi/pulumi-kubernetes-cert-manager#16]
### What happened?

When trying to deploy cert manager, I get the same warning that should be fixed in issue#14
` warning: resource plugin kubernetes-cert-manager is expected to have version >=0.0.3, but has 0.0.1; the wrong version may be on your path, or this may be a bug in the plugin`

### Steps to reproduce

put the example with my own "settings"

npm install  @pulumi/kubernetes-cert-manager

run a pulumi up

### Expected Behavior

The warning shouldn't appear

### Actual Behavior

bad version reported

### Output of `pulumi about`

```
CLI
Version      3.47.1
Go Version   go1.19.2
Go Compiler  gc

Plugins
NAME                     VERSION
azure-native             1.40.0
azuread                  5.6.0
kubernetes               3.8.2
kubernetes-cert-manager  0.0.3
nodejs                   unknown
random                   4.3.1

Host
OS       Microsoft Windows 11 Pro
Version  10.0.22000 Build 22000
Arch     x86_64
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
Hi @JonAStorelv - please try with v0.0.5 which should have successfully published a version. :)

Fixed in #17
