### ISSUE TITLE
"no resource plugin 'kubernetes-cert-manager-v3.9.0' found in the workspace" When Trying to Use Lib

### ISSUE THREAD

**Issue by froomzy** [pulumi/pulumi-kubernetes-cert-manager#3]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I am using python, and want to get cert-manager running in a k8s cluster. So I found and installed `pulumi-kubernetes-cert-manager` as that seems to wrap what I want. I added a declaration for a cert-manager and a Lets Encrypt staging issuer, following the examples in this repo. When I try `pulumi up` I get the following error:

```
pulumi:providers:kubernetes-cert-manager (default_3_9_0):
    error: no resource plugin 'kubernetes-cert-manager-v3.9.0' found in the workspace or on your $PATH, install the plugin using `pulumi plugin install resource kubernetes-cert-manager v3.9.0`
```

### Steps to reproduce

1. Install cert-manager library into venv
```
pip install pulumi-kubernetes-cert-manager
```
2.  Create cert-manager 
```python
import pulumi
import pulumi_kubernetes as k8s
import pulumi_kubernetes_cert_manager as cert_manager


def create_certificate_manager(*, kube_config: do.outputs.KubernetesClusterKubeConfig):
    custom_provider = get_provider(kube_config=kube_config)
    options = pulumi.ResourceOptions(
        provider=custom_provider
    )

    namespace = k8s.core.v1.Namespace(
        "k8s-cert-manager-staging",
        metadata={
            "name": "k8s-cert-manager-staging"
        },
        opts=options
    )

    # Install a cert manager into our cluster.
    manager = cert_manager.CertManager(
        'cert-manager',
        install_crds=True,
        helm_options=cert_manager.ReleaseArgs(
            namespace="k8s-cert-manager-staging",
        ),
        opts=options,
    )
```
3. Run `pulumi up`

Expected:  Pulumi to create the cert-manager, or at least error because I had the cert-manager creation wrong
Actual:  Get an error about not having the right plugin installed
```
pulumi:providers:kubernetes-cert-manager (default_3_9_0):
    error: no resource plugin 'kubernetes-cert-manager-v3.9.0' found in the workspace or on your $PATH, install the plugin using `pulumi plugin install resource kubernetes-cert-manager v3.9.0`
```

**Comment by leezen** [comment]
I think what's happening is because you have

```
options = pulumi.ResourceOptions(
        provider=custom_provider
    )
```

and passing that into the `cert_manager.CertManager` resource, there's some confusion about provider versions and what provider to actually use here (I'm guessing the `v3.9.0` is actually coming from your `pulumi-kubernetes` version).

If you provide

```
pulumi.ResourceOptions(
    providers={ 'kubernetes': custom_provider }
)
```

instead for the `CertManager` resource, does this solve the issue for you?

**Comment by froomzy** [comment]
Yup, that was it. Im guessing just a bit of a newb not understanding how all the things hang togeather yet. Thanks very much for the help.

**Comment by leezen** [comment]
@froomzy No problem at all. I think the error message could be clearer and this is a very understandable mistake that should have a clearer warning.
