### ISSUE TITLE
Add an `arm64` build for the plugin

### ISSUE THREAD

**Issue by jtweaver** [pulumi/pulumi-kubernetes-cert-manager#4]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I'm unable to install the plugin. I started with the typescript example and installed the package via npm. Run `pulumi up` and get this:

```
error: no resource plugin 'kubernetes-cert-manager-v0.0.1' found in the workspace or on your $PATH, install the plugin using `pulumi plugin install resource kubernetes-cert-manager v0.0.1`
```

Trying to install plugin manually:
```
$ pulumi plugin install resource kubernetes-cert-manager v0.0.1
[resource plugin kubernetes-cert-manager-0.0.1] installing
error: [resource plugin kubernetes-cert-manager-0.0.1] downloading from : 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-kubernetes-cert-manager-v0.0.1-darwin-arm64.tar.gz
```

Code (deploying against local kubeconfig):
```
import * as k8s from "@pulumi/kubernetes";
import * as certmanager from "@pulumi/kubernetes-cert-manager";

const nsName = "cert-manager";
const ns = new k8s.core.v1.Namespace("cert-manager", {
  metadata: { name: nsName },
});

// Install cert-manager into our cluster.
const manager = new certmanager.CertManager("cert-manager", {
  installCRDs: true,
  helmOptions: {
    namespace: nsName,
  },
});
```

### Steps to reproduce

1. Set up a new Pulumi typescript project
2. `npm i @pulumi/kubernetes-cert-manager`
3. Copy the code from the example
4. `pulumi up`

Expected: Cert-manager to be installed
Actual: The error above.

**Comment by leezen** [comment]
There currently isn't an `arm64` build for this component. We'll need to add that and start publishing it.

**Comment by jtweaver** [comment]
This should be reopened. There still appears to be no arm build

```
error: [resource plugin kubernetes-cert-manager-0.0.1] downloading from : 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-kubernetes-cert-manager-v0.0.1-darwin-arm64.tar.gz
```

**Comment by omercnet** [comment]
@leezen please reopen this

**Comment by omercnet** [comment]
@stack72 seems like you added arm64 build but still needs rebuilding and publishing
https://github.com/pulumi/pulumi-kubernetes-cert-manager/commit/a95d19270a8c3ee16ea8e5db6170fc3ee62cbd44

**Comment by stack72** [comment]
We just cut a new release of this provider that has the correct arm64 build now - apologies for this! We will ensure that this doesn't fall through the cracks going forward

**Comment by zerbitx** [comment]
I'm still seeing this.  I was able to get around it by cloning the repo and running `make install_provider`

**Comment by dustingraves** [comment]
> I'm still seeing this. I was able to get around it by cloning the repo and running `make install_provider`

What did you have to do to reference it after you built it in the repo?

**Comment by dustingraves** [comment]
Figured it out. 

Leaving this here for anyone else who gets pulled into an older project with an M1 mac.

make sure you have `golang` installed 
1. `git clone git@github.com:pulumi/pulumi-kubernetes-cert-manager.git && cd pulumi-kubernetes-cert-manager` 
2.  run `make install_provider`
3. `mkdir ~/.pulumi/plugins/resource-kubernetes-cert-manager-v0.0.1`
4. `cp bin/pulumi-resource-kubernetes-cert-manager ~/.pulumi/plugins/resource-kubernetes-cert-manager-v0.0.1/`
